// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpI-Ww5nwvmKpXSL5srtexDZPxbgLP2EE',
    appId: '1:923401738084:web:290132e18c10d12f76cc71',
    messagingSenderId: '923401738084',
    projectId: 'to-do-list-d36c9',
    authDomain: 'to-do-list-d36c9.firebaseapp.com',
    storageBucket: 'to-do-list-d36c9.appspot.com',
    measurementId: 'G-ESGTLQTY9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnUgOAiijrcpE6F1XAIWNk8DElI_po-vc',
    appId: '1:923401738084:android:3d41f2e663f0a3be76cc71',
    messagingSenderId: '923401738084',
    projectId: 'to-do-list-d36c9',
    storageBucket: 'to-do-list-d36c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk5yqPSPyUY13DvsPFk_Tmr-2q74ZzM38',
    appId: '1:923401738084:ios:91492a1e0b58bea376cc71',
    messagingSenderId: '923401738084',
    projectId: 'to-do-list-d36c9',
    storageBucket: 'to-do-list-d36c9.appspot.com',
    iosBundleId: 'com.example.baseTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk5yqPSPyUY13DvsPFk_Tmr-2q74ZzM38',
    appId: '1:923401738084:ios:e2acdfcd55a2fec976cc71',
    messagingSenderId: '923401738084',
    projectId: 'to-do-list-d36c9',
    storageBucket: 'to-do-list-d36c9.appspot.com',
    iosBundleId: 'com.example.baseTodolist.RunnerTests',
  );
}
